<?php

namespace App\Http\Middleware;


use Closure;
use Illuminate\Http\Response;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;

/**
 *
 *  @class: authenticate
 *
 *  @purpose: to perform any actions that are required for the user to authorized or authenticated
 *
 */


class Authenticate
{

    public function handle(Request $request, Closure $next, $guard = null)
    {
        // Auth HEADERS

        // change this to be header instead of cookie for each request
        // we will change this to be header instead of cookie for each request
        // and will have this following structure

        /**
         *   @RequestStructure:
         *
         *          AccessToken: <TOKEN> // this is the token that is generated by the server
         *          GroupHandShake: <GROUP_HANDSHAKE> // stores handshake of the group
         *          UserHandShake: <USER_HANDSHAKE> // users handshake
         *          LastRequestHandShake: <LAST_REQUEST_HANDSHAKE> // this will follow our requests and will be used to check if the request is valid or not
         *          Elipsis: <ELIPSIS> // this is the elipsis that is used to check if the request is valid or not this is a 1024 key that is generated by the server
         *          if the request is valid then the server will return the following structure
         *
         */
        if (!empty($_COOKIE['accessToken'])) {
            // check if the access token is valid
            $userExist = DB::table('users')->where('remember_token', $_COOKIE['accessToken'])->exists();
            if ($userExist) {
                // access token is valid
                return $next($request);
            } else {
                // access token is not valid
                return response()->json([
                    'authenticated' => false,
                    'message' => 'Access Token is not valid', 'error' => 'Access Token is not valid'], 401);
            }
        } else {
            // tood - add a check for the access token in the header
            // check if the access token is valid
            return $next($request);
    }
}
    /**
     *
     *  @method: getTokenFromHeader
     *
     *
     *  @purpose: to get the token from the header TO AUTHENTICATE ANY REST API REQUESTS
     *
     */


    private function getTokenFromHeader(Request $request, Closure $next, $guard = null)
    {
        $header = $request->header('Authorization');
        if (!empty($header)) {
            $token = explode(' ', $header)[1];
            return $token;
        }
        return null;
    }

}
